apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: class-config-map-template
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: cluster-aas-operator
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: claas-config
      namespace: cluster-aas-operator
    data:  
      argocd-ns: argocd
